##### Buzzard v2.0 imput files
## copacabana master files
members_infile   : /data/des61.a/data/johnny/Buzzard/Buzzard_v2.0.0/y3/tiles/buzzard_y3_v2.0.0_golden_{:02d}.hdf
cluster_infile   : /data/des61.a/data/johnny/Buzzard/Buzzard_v2.0.0/y3/halos/buzzard_y3_v2.0.0_golden_halos.fits
master_outfile   : /data/des61.a/data/johnny/Buzzard/Buzzard_v2.0.0/y3/output/buzzard_v2.0.0_copa_golden_{:05d}.hdf5
columns_yaml_file: /home/s1/jesteves/git/ccopa/config_files/buzzard_v2_grc_columns.yaml
pixelmap_file    : 


######## copa setup #######
zmin_gal: 0.0
zmax_gal: 1.5
dz_max  : 0.3

## radial cuts
rmax : 3.
r_in : 4.
r_out: 6.

## pz0 factor
pz_factor: 1.

## relative mag cut
mag_model_file: /home/s1/jesteves/git/ccopa/aux_files/annis_mags_04_Lcut.txt
dmag_lim: 1

## cluster aperture radii, it can be a number in Mpc, values: rhod/r200 (simulation)
r_aper_model : r200
r_aper_value : 

## parallel process
copa_number_of_chunks: 100

## Photo-z setup
# 1st model: a gaussian distribution centered on zcls with a std of z_window
# 2nd model: a gaussian distribution centered on zcls+bias with a std dependeding on redshift
# 2nd model is a text file with: z, bias, std
z_window     : 0.03
z_model_file : /home/s1/jesteves/git/ccopa/aux_files/zwindow_model_buzzard_dnf.txt

## Healpixel config
healpixel_setup : True
healpixel_list  : [32,34]
# healpixel_list  : [0, 16, 17, 18, 19, 20, 22, 32, 33, 34, 35, 38, 44, 45, 46, 47]
## for the whole sample use the pixel list below


######## bma setup #######
## paralell
bma_number_of_chunks: 500

## stellar population libray file
lib_inPath: /data/des61.a/data/pbarchi/galaxyClusters/simha_miles_Nov2016/

